"""empty message

Revision ID: a286fbb85d2d
Revises: 
Create Date: 2017-05-11 11:39:06.397563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a286fbb85d2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('remoteusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remoteusers_email'), 'remoteusers', ['email'], unique=True)
    op.create_index(op.f('ix_remoteusers_first_name'), 'remoteusers', ['first_name'], unique=False)
    op.create_index(op.f('ix_remoteusers_last_name'), 'remoteusers', ['last_name'], unique=False)
    op.create_index(op.f('ix_remoteusers_username'), 'remoteusers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remoteusers_username'), table_name='remoteusers')
    op.drop_index(op.f('ix_remoteusers_last_name'), table_name='remoteusers')
    op.drop_index(op.f('ix_remoteusers_first_name'), table_name='remoteusers')
    op.drop_index(op.f('ix_remoteusers_email'), table_name='remoteusers')
    op.drop_table('remoteusers')
    op.drop_table('roles')
    # ### end Alembic commands ###
