"""empty message

Revision ID: f3f327ab19e9
Revises: a286fbb85d2d
Create Date: 2017-05-12 12:57:19.553197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f327ab19e9'
down_revision = 'a286fbb85d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deptors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullnames', sa.String(length=100), nullable=True),
    sa.Column('mobilenumber', sa.Integer(), nullable=True),
    sa.Column('nationalid', sa.Integer(), nullable=True),
    sa.Column('deptamount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fullnames')
    )
    op.create_index(op.f('ix_deptors_deptamount'), 'deptors', ['deptamount'], unique=False)
    op.create_index(op.f('ix_deptors_mobilenumber'), 'deptors', ['mobilenumber'], unique=True)
    op.create_index(op.f('ix_deptors_nationalid'), 'deptors', ['nationalid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deptors_nationalid'), table_name='deptors')
    op.drop_index(op.f('ix_deptors_mobilenumber'), table_name='deptors')
    op.drop_index(op.f('ix_deptors_deptamount'), table_name='deptors')
    op.drop_table('deptors')
    # ### end Alembic commands ###
